version: "3.2"

services:
  web:
    build: 
      context : .
      dockerfile: Dockerfile
    networks:
      - examplenetwork
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: always


  db:
    image: postgres
    networks:
      - examplenetwork
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin 
      - POSTGRES_DATABASE=postgres

networks:
  examplenetwork: 

volumes:
  postgresql:
  postgresql_data: